In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [2]:
df = pd.read_csv("./melbourne_house_overfitting.csv")
df

Rooms  Propertycount  Distance  Bedroom2  Bathroom  Car    Landsize  \
0          2         4019.0       2.5       2.0       1.0  1.0  202.000000   
1          2         4019.0       2.5       2.0       1.0  0.0  156.000000   
2          3         4019.0       2.5       3.0       2.0  0.0  134.000000   
3          3         4019.0       2.5       3.0       2.0  1.0   94.000000   
4          4         4019.0       2.5       3.0       1.0  2.0  120.000000   
...      ...            ...       ...       ...       ...  ...         ...   
27239      4         6543.0       6.3       4.0       1.0  3.0  593.000000   
27240      2         6543.0       6.3       2.0       2.0  1.0   98.000000   
27241      2         6543.0       6.3       2.0       1.0  2.0  220.000000   
27242      3         6543.0       6.3       0.0       0.0  0.0  593.598993   
27243      2         6543.0       6.3       2.0       1.0  0.0  250.000000   

       BuildingArea      Price  Suburb_Aberfeldie  ...  \
0          160.2564  1480000.0                  0  ...   
1           79.0000  1035000.0                  0  ...   
2          150.0000  1465000.0                  0  ...   
3          160.2564   850000.0                  0  ...   
4          142.0000  1600000.0                  0  ...   
...             ...        ...                ...  ...   
27239      160.2564  1480000.0                  0  ...   
27240      104.0000   888000.0                  0  ...   
27241      120.0000   705000.0                  0  ...   
27242      160.2564  1140000.0                  0  ...   
27243      103.0000  1020000.0                  0  ...   

       CouncilArea_Moorabool Shire Council  CouncilArea_Moreland City Council  \
0                                        0                                  0   
1                                        0                                  0   
2                                        0                                  0   
3                                        0                                  0   
4                                        0                                  0   
...                                    ...                                ...   
27239                                    0                                  0   
27240                                    0                                  0   
27241                                    0                                  0   
27242                                    0                                  0   
27243                                    0                                  0   

       CouncilArea_Nillumbik Shire Council  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   
...                                    ...   
27239                                    0   
27240                                    0   
27241                                    0   
27242                                    0   
27243                                    0   

       CouncilArea_Port Phillip City Council  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
...                                      ...   
27239                                      0   
27240                                      0   
27241                                      0   
27242                                      0   
27243                                      0   

       CouncilArea_Stonnington City Council  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                  

In [3]:
X = df.drop('Price', axis=1)
y = df['Price']

In [4]:
X

Rooms  Propertycount  Distance  Bedroom2  Bathroom  Car    Landsize  \
0          2         4019.0       2.5       2.0       1.0  1.0  202.000000   
1          2         4019.0       2.5       2.0       1.0  0.0  156.000000   
2          3         4019.0       2.5       3.0       2.0  0.0  134.000000   
3          3         4019.0       2.5       3.0       2.0  1.0   94.000000   
4          4         4019.0       2.5       3.0       1.0  2.0  120.000000   
...      ...            ...       ...       ...       ...  ...         ...   
27239      4         6543.0       6.3       4.0       1.0  3.0  593.000000   
27240      2         6543.0       6.3       2.0       2.0  1.0   98.000000   
27241      2         6543.0       6.3       2.0       1.0  2.0  220.000000   
27242      3         6543.0       6.3       0.0       0.0  0.0  593.598993   
27243      2         6543.0       6.3       2.0       1.0  0.0  250.000000   

       BuildingArea  Suburb_Aberfeldie  Suburb_Airport West  ...  \
0          160.2564                  0                    0  ...   
1           79.0000                  0                    0  ...   
2          150.0000                  0                    0  ...   
3          160.2564                  0                    0  ...   
4          142.0000                  0                    0  ...   
...             ...                ...                  ...  ...   
27239      160.2564                  0                    0  ...   
27240      104.0000                  0                    0  ...   
27241      120.0000                  0                    0  ...   
27242      160.2564                  0                    0  ...   
27243      103.0000                  0                    0  ...   

       CouncilArea_Moorabool Shire Council  CouncilArea_Moreland City Council  \
0                                        0                                  0   
1                                        0                                  0   
2                                        0                                  0   
3                                        0                                  0   
4                                        0                                  0   
...                                    ...                                ...   
27239                                    0                                  0   
27240                                    0                                  0   
27241                                    0                                  0   
27242                                    0                                  0   
27243                                    0                                  0   

       CouncilArea_Nillumbik Shire Council  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   
...                                    ...   
27239                                    0   
27240                                    0   
27241                                    0   
27242                                    0   
27243                                    0   

       CouncilArea_Port Phillip City Council  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   
...                                      ...   
27239                                      0   
27240                                      0   
27241                                      0   
27242                                      0   
27243                                      0   

       CouncilArea_Stonnington City Council  \
0                                         0   
1                                         0   
2        

In [5]:
y

0        1480000.0
1        1035000.0
2        1465000.0
3         850000.0
4        1600000.0
           ...    
27239    1480000.0
27240     888000.0
27241     705000.0
27242    1140000.0
27243    1020000.0
Name: Price, Length: 27244, dtype: float64

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)


In [10]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [11]:
lr.score(X_train, y_train)

0.6827792395792723

In [12]:
lr.coef_

array([ 2.64001655e+05,  4.92118905e+00, -4.64732744e+04, -8.22349031e+04,
        1.17151153e+05,  4.29703140e+04,  2.35173742e+00,  4.70024530e+02,
        2.61342069e+05, -4.61008827e+04, -1.32312259e+05,  2.15453995e+05,
        1.20133839e+05,  2.72683980e+05,  1.74702166e+05, -8.00201053e+04,
       -1.50967673e+05, -4.94461444e+04,  1.17711126e+05, -1.28880253e+05,
       -3.49349656e+04, -8.54261329e+03,  6.19157896e+04, -2.57258028e+05,
       -1.10868116e+05, -2.42391674e+05,  1.79856957e+05, -1.22395100e+05,
        2.04625284e+05,  3.78258911e+04,  1.46681364e+05,  2.32198627e+03,
        7.35395734e+04, -5.29198413e+04,  1.90482393e+05, -3.20451670e+05,
        7.49515013e+04, -2.83019804e+04,  2.69103300e+04,  2.78824270e+05,
        1.51386730e+05, -1.06324212e+05, -8.45087700e+04,  2.96568248e+05,
        1.50644588e+05, -2.19792128e-07,  1.75999576e+05, -1.20057166e+05,
       -9.64544651e+03,  3.68377378e+05, -1.35478625e+05, -6.38092125e+04,
        3.53493139e+04,  

In [13]:
from sklearn.linear_model import Ridge

In [20]:
ridge = Ridge(alpha=2, max_iter=100, tol=0.1)
ridge.fit(X_train, y_train)

Ridge(alpha=2, max_iter=100, tol=0.1)

In [21]:
ridge.score(X_train, y_train)

0.6787710286515469

In [22]:
ridge.score(X_test, y_test)

0.672848837594467

In [23]:
ridge.coef_

array([ 2.72552411e+05,  1.53692445e+00, -3.52811442e+04, -8.57921812e+04,
        1.23850461e+05,  4.29312628e+04,  2.45654403e+00,  4.42970290e+01,
        2.46900673e+05, -8.54112583e+04, -1.15534044e+05,  2.28032535e+05,
        1.28454725e+05,  2.60590859e+05,  1.46242740e+05, -1.16519452e+05,
       -1.46664045e+05, -4.32229928e+04,  1.15984753e+05, -8.14602181e+04,
       -6.82585907e+04, -2.52637410e+04,  5.78264171e+04, -2.14091425e+05,
       -6.94658946e+04, -2.52378554e+05,  5.79138740e+04, -1.35721795e+05,
        1.95158619e+05,  3.19912197e+04,  1.07144920e+05, -2.30599112e+04,
        6.55777572e+04, -1.98705254e+04,  1.50625672e+05, -2.67994451e+05,
        5.91231662e+04, -4.97806754e+04,  7.04942815e+04,  2.15061688e+05,
        1.53120607e+05, -9.50805888e+04, -7.71815859e+04,  1.82771262e+05,
        1.10655334e+05,  0.00000000e+00,  1.91713867e+05, -1.41640557e+05,
       -5.32607725e+04,  4.19663641e+05, -8.83855753e+04, -7.89803192e+03,
        3.46935084e+04,  

# using Lasso Regression

In [24]:
# using Lasso Regression

from sklearn.linear_model import Lasso

In [27]:
lasso = Lasso(alpha=50, max_iter=100, tol=0.1)

lasso.fit(X_train, y_train)


c:\Python312\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:678: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.327e+15, tolerance: 7.963e+14
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=50, max_iter=100, tol=0.1)

In [28]:
lasso.score(X_train,y_train)

0.6766985624766824

In [29]:
lasso.score(X_test, y_test)

0.6636111369404489

In [30]:
lasso.coef_

array([ 2.70967779e+05,  4.63745956e+00, -3.03357705e+04, -8.48946624e+04,
        1.23220366e+05,  4.17503159e+04,  2.56283488e+00,  8.65129010e+01,
        2.19220733e+05, -1.20065548e+05, -0.00000000e+00,  3.24095470e+05,
        1.55485391e+05,  2.97071682e+05,  1.38140476e+05, -9.41251645e+04,
       -1.30121499e+05, -0.00000000e+00,  1.51646664e+05, -9.60503347e+04,
       -1.74328672e+04, -0.00000000e+00,  2.29652095e+04, -1.42906742e+05,
       -0.00000000e+00, -2.72295256e+05,  0.00000000e+00, -3.51581901e+04,
        2.31085764e+05,  6.08260117e+04,  3.20753304e+04, -0.00000000e+00,
        0.00000000e+00, -0.00000000e+00,  1.90154504e+05, -1.90416055e+05,
        3.35876186e+04, -8.78863211e+04,  5.12664874e+04,  2.57628933e+05,
        1.86342954e+05, -5.53309467e+03, -0.00000000e+00,  6.29880653e+04,
        1.70718008e+04,  0.00000000e+00,  2.46076632e+05, -1.20882624e+05,
       -0.00000000e+00,  4.88763467e+05, -0.00000000e+00,  1.27428350e+04,
        0.00000000e+00,  