## Numpy

#### NumPy, which stands for Numerical Python, is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [2]:
import numpy as np

In [3]:
arr = np.array([2,45,6,7,1,17,171])
print(arr)

[  2  45   6   7   1  17 171]


In [4]:
type(arr)

numpy.ndarray

## 1D, 2D , 3d Array

#### Numpy Array vs Python List

#### Homogenous Data Type --- Numpy have same data Type  
#### Hetrogenous Data Type --- List can contain element of different type

In [5]:
lst = [3,4,6,7,2,7,12,True, 'a','b']
lst

[3, 4, 6, 7, 2, 7, 12, True, 'a', 'b']

In [6]:
arr = np.array([2,4,6,8,32,True, 'a', 3.6])
arr

array(['2', '4', '6', '8', '32', 'True', 'a', '3.6'], dtype='<U32')

In [7]:
type(arr)

numpy.ndarray

#### Vectorized operations in NumPy refer to the ability to perform operations on entire arrays rather than on a single element at a time. This is possible due to NumPy's broadcasting feature. This makes the computations faster and code cleaner.

#### Here's an example of vectorized operations:
```

In [8]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [9]:
arr = np.array([1,2,4,5,7,8]) * 2
arr

array([ 2,  4,  8, 10, 14, 16])

In [10]:
lst = [1,2,4,5,6,8]
lst

[1, 2, 4, 5, 6, 8]

In [11]:
lst = [1,2,4,5,6,8] * 2
lst

[1, 2, 4, 5, 6, 8, 1, 2, 4, 5, 6, 8]

In [12]:
lst = [1,2,4,5,6,8]
l = []

for i in lst :
    l.append(i*2)

l

[2, 4, 8, 10, 12, 16]

#### Performance: NumPy arrays are more efficient than Python lists when it comes to numerical operations. NumPy uses less memory, is faster, and is more convenient to use for mathematical and scientific computations.



In [13]:
list(range(1,11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [14]:
[i**2 for i in list(range(1,11))]

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [15]:
%timeit [i**2 for i in list(range(1,11))]

1.15 µs ± 181 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
np.arange(1,11,1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(1,11) ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [18]:
%timeit np.arange(1,11) ** 2

1.73 µs ± 20.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [19]:
%timeit [i**2 for i in list(range(1,1001))]

76.9 µs ± 2.66 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [20]:
%timeit np.arange(1,1001) ** 2

3.37 µs ± 237 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


### Numpy Functionalities

In [21]:
### Creation of 1D 2D and 3D Array

arr = np.array([1,2,3,5,6,7])
arr

array([1, 2, 3, 5, 6, 7])

In [22]:
arr.ndim

1

In [23]:
arr.shape

(6,)

In [24]:
arr2 = np.array([[1,2,3,4,5,6]])
arr2

array([[1, 2, 3, 4, 5, 6]])

In [25]:
arr2.ndim

2

In [26]:
arr2.shape

(1, 6)

In [27]:

arr2 = np.array([[1,2,3,4,5,6], [7,8,9,20,22,23], [24,26,14,16,19,20]])
arr2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 20, 22, 23],
       [24, 26, 14, 16, 19, 20]])

In [28]:
arr2.shape

(3, 6)

In [29]:
arr2.ndim

2

## 3D

In [30]:
arr3 = np.array([[[1,2,3,4,5]]])
arr3

array([[[1, 2, 3, 4, 5]]])

In [31]:
arr3.ndim

3

In [32]:
arr3.shape

(1, 1, 5)

In [33]:
arr3 = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [34]:
arr3.ndim

3

In [35]:

arr3.shape

(2, 2, 3)

In [36]:
arr32 = np.array([1,2,3,4,5], ndmin=32)
print(arr32.shape)

(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 5)


## Special Numpy Operation

In [37]:
arr0 = np.zeros(5)
arr0

array([0., 0., 0., 0., 0.])

In [38]:
arr0 = np.zeros([3,3])
arr0

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
arr0 = np.zeros([2,3,3], dtype = "int")
arr0

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [43]:
arr0 = np.zeros([3,3,3], dtype = "int")
arr0

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [46]:
arr1 = np.ones([3,4], dtype="int")
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [47]:
arr1 = np.ones([3,4,5], dtype="int")
arr1

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [50]:
arr = np.full([3,3], 5)
arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [55]:
arr = np.full([3,4,5], "a")
arr

array([[['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a']],

       [['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a']],

       [['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a'],
        ['a', 'a', 'a', 'a', 'a']]], dtype='<U1')

In [56]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [65]:
arr = np.linspace(1,100,20)
arr

array([  1.        ,   6.21052632,  11.42105263,  16.63157895,
        21.84210526,  27.05263158,  32.26315789,  37.47368421,
        42.68421053,  47.89473684,  53.10526316,  58.31578947,
        63.52631579,  68.73684211,  73.94736842,  79.15789474,
        84.36842105,  89.57894737,  94.78947368, 100.        ])

In [66]:
6.21052632 -1

5.21052632

In [67]:
11.42105263 - 6.21052632

5.2105263100000005

In [68]:
arr = np.linspace(1,100,20).astype(int)
arr

array([  1,   6,  11,  16,  21,  27,  32,  37,  42,  47,  53,  58,  63,
        68,  73,  79,  84,  89,  94, 100])

### Random Operations


In [70]:
from numpy import random

In [74]:
arr = random.randint(1,100, 10)
arr

array([36,  2, 65, 38, 86, 45, 41, 79, 56, 42])

In [78]:
arr = random.randint(100, size=(3,3))
arr

array([[16, 36, 46],
       [37, 90,  1],
       [89, 63, 29]])

In [79]:
arr = random.randint(100, size=(3,4,3))
arr

array([[[62, 55, 53],
        [95, 45, 17],
        [88, 20, 41],
        [33, 38, 40]],

       [[56, 77, 78],
        [ 7, 78, 49],
        [39, 94, 99],
        [88, 54, 56]],

       [[66, 43, 83],
        [ 9, 97,  0],
        [76, 73, 22],
        [40, 88, 70]]])

In [81]:
arr = random.rand()
arr

0.24965257802760177

In [82]:
arr = random.rand(5)
arr

array([0.71469258, 0.83827963, 0.98187073, 0.57623731, 0.82255901])

In [83]:
arr = random.rand(5,5)
arr

array([[0.64743951, 0.18556429, 0.93559472, 0.22557465, 0.4676102 ],
       [0.2653396 , 0.5902102 , 0.65002962, 0.62431134, 0.42386431],
       [0.92524643, 0.76453997, 0.27581055, 0.48632022, 0.70748821],
       [0.48668804, 0.15087823, 0.99317668, 0.16467319, 0.88168702],
       [0.11599096, 0.93082356, 0.11919605, 0.58856346, 0.54242614]])

In [84]:

arr = random.rand(3,4,5)
arr

array([[[0.9601045 , 0.97639965, 0.87793752, 0.21641321, 0.77380137],
        [0.75614855, 0.97707873, 0.34144022, 0.09824833, 0.12890808],
        [0.74043747, 0.39749778, 0.21078739, 0.97274557, 0.30201176],
        [0.14681262, 0.42578902, 0.12115263, 0.42884138, 0.44713369]],

       [[0.42231854, 0.76850952, 0.95192164, 0.22294148, 0.41339536],
        [0.68428906, 0.05012925, 0.34516176, 0.34942574, 0.35262702],
        [0.65278318, 0.34507738, 0.81670668, 0.50290649, 0.67663913],
        [0.62042224, 0.49151933, 0.16398305, 0.14759113, 0.19323422]],

       [[0.46335935, 0.45257156, 0.34454816, 0.1765282 , 0.90574041],
        [0.69392889, 0.03429084, 0.47027503, 0.96523309, 0.96709075],
        [0.63005102, 0.47663527, 0.97634031, 0.79827749, 0.82115166],
        [0.69812457, 0.3796985 , 0.29479741, 0.53831505, 0.00448763]]])

In [92]:
arr = (np.random.rand(3, 4, 5) * 100).astype(int)
arr

array([[[88, 85, 87, 83, 45],
        [69, 36, 33, 87, 27],
        [12, 21, 27, 22, 15],
        [ 8, 66, 40, 43, 82]],

       [[44, 98, 51, 82, 94],
        [62,  4, 31,  8,  6],
        [92, 96, 21, 74, 89],
        [79, 52, 95, 98, 71]],

       [[24, 91, 87, 30, 93],
        [20,  3, 49,  5, 98],
        [45, 53, 66, 12, 70],
        [95, 78, 93, 37, 11]]])

In [90]:
arr = random.choice([3,4,5,7,9,23], size=6)
arr

array([ 4,  4,  5,  3, 23,  9])

In [95]:
arr = random.choice([3,4,5,7,9,23], size=(4,3,3))
arr

array([[[ 4,  3, 23],
        [ 5,  3,  5],
        [ 3,  4,  3]],

       [[23,  7,  3],
        [ 3,  7, 23],
        [23,  9,  3]],

       [[ 5, 23,  9],
        [ 5,  9, 23],
        [ 3, 23,  7]],

       [[ 7,  4, 23],
        [23,  9, 23],
        [ 5,  5,  4]]])

In [96]:
arr = random.choice([3,4,5,7,9,23], size=100)
arr

array([ 9,  9,  4,  5,  7,  9, 23,  3,  4,  4,  3,  5,  9,  4, 23,  5,  9,
        7,  9,  4,  9,  3,  5,  7,  9,  3,  9,  4,  5, 23, 23,  4,  4,  9,
        3, 23,  5, 23, 23,  3,  7,  9,  7,  5,  3,  5,  3, 23,  3,  7,  3,
       23,  7, 23, 23,  9,  7,  4,  3,  4,  3,  9,  4, 23,  3, 23,  5,  5,
        7,  5, 23,  3,  4, 23,  9,  5,  4, 23,  4,  7, 23,  5,  5, 23,  3,
        4,  5,  5,  3,  9,  4,  3,  9,  7,  5,  3,  7, 23, 23,  7])

In [99]:
arr = random.choice([3,5,7,8], p=[0.1,0.0,0.6,0.3], size=100)
arr

array([7, 3, 8, 8, 7, 3, 8, 8, 7, 7, 8, 7, 7, 7, 8, 7, 8, 7, 7, 7, 7, 7,
       7, 7, 7, 7, 7, 7, 8, 7, 7, 7, 8, 7, 7, 8, 8, 7, 8, 7, 8, 7, 7, 7,
       7, 8, 7, 7, 3, 7, 3, 8, 8, 3, 7, 3, 8, 8, 7, 7, 7, 3, 8, 8, 7, 8,
       7, 7, 7, 8, 8, 7, 7, 8, 8, 7, 7, 7, 3, 8, 7, 7, 7, 7, 8, 8, 8, 7,
       3, 8, 7, 8, 8, 7, 7, 8, 8, 7, 8, 8])

In [103]:
arr = random.choice([3,5,7,8,9,11], p=[0.1,0.0,0.6,0.3,0.0,0.0], size=(3,4,5))
arr

array([[[7, 7, 3, 7, 7],
        [8, 7, 8, 7, 3],
        [8, 8, 8, 7, 8],
        [7, 8, 7, 7, 8]],

       [[7, 8, 7, 7, 8],
        [3, 7, 7, 3, 7],
        [8, 8, 3, 7, 7],
        [7, 7, 7, 7, 3]],

       [[7, 8, 7, 7, 8],
        [7, 7, 7, 7, 8],
        [8, 7, 8, 8, 7],
        [7, 7, 8, 7, 3]]])

### Data Types and Memory Management

In [104]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [108]:
arr = np.array([1,2,3,4,5])
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int32

 [1 2 3 4 5]


In [109]:
arr = np.array([1,2,3,4,5], dtype =float)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  float64

 [1. 2. 3. 4. 5.]


In [113]:
arr = np.array([1,2,3,4,5], np.int8)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int8

 [1 2 3 4 5]


In [115]:
arr = np.array([1,12,3,4,5], np.int8)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int8

 [ 1 12  3  4  5]


In [116]:
arr = np.array([1,129,3,4,5], np.int8)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int8

 [   1 -127    3    4    5]


C:\Users\patid\AppData\Local\Temp\ipykernel_25944\1162322270.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([1,129,3,4,5], np.int8)


In [117]:
arr = np.array([1,-129,3,4,5], np.int8)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int8

 [  1 127   3   4   5]


C:\Users\patid\AppData\Local\Temp\ipykernel_25944\3578505770.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr = np.array([1,-129,3,4,5], np.int8)


In [119]:
arr = np.array([1,-1239,3,4,5], np.int16)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int16

 [    1 -1239     3     4     5]


In [120]:
arr = np.array([1,1239,3,4,5], np.int16)
print(f'Data Types :  {arr.dtype}')
print("\n",arr)

Data Types :  int16

 [   1 1239    3    4    5]


### Arithmatic Operations

In [122]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [123]:
arr = np.array([1,2,3,4,5]) * 10
arr

array([10, 20, 30, 40, 50])

In [124]:
arr = np.array([1,2,3,4,5]) -10
arr

array([-9, -8, -7, -6, -5])

In [125]:
arr = np.array([1,2,3,4,5]) + 10
arr

array([11, 12, 13, 14, 15])

In [126]:
arr = np.array([1,2,3,4,5]) / 10
arr

array([0.1, 0.2, 0.3, 0.4, 0.5])

In [127]:

arr = np.array([1,2,3,4,5]) // 10
arr


array([0, 0, 0, 0, 0], dtype=int32)

In [128]:
arr = np.array([1,2,3,4,5]) %2
arr

array([1, 0, 1, 0, 1], dtype=int32)

In [129]:
arr = np.array([1,2,3,4,5]) *10 -10
arr

array([ 0, 10, 20, 30, 40])

In [130]:
arr = np.array([1,2,3,4,5]) ** 2

arr

array([ 1,  4,  9, 16, 25])

### Arithmatic Operation using Built in Function

In [136]:
arr = np.array([1,2,3,4,5])
arr2 = np.array([2,4,6,8,9])

sum(arr + arr2)

44

In [137]:
np.add(arr, arr2)

array([ 3,  6,  9, 12, 14])

In [140]:
np.subtract(arr,arr2)

array([-1, -2, -3, -4, -4])

In [141]:
np.multiply(arr,arr2)

array([ 2,  8, 18, 32, 45])

In [142]:
np.divide(arr,arr2)

array([0.5       , 0.5       , 0.5       , 0.5       , 0.55555556])

In [144]:
np.floor_divide(arr,arr2)

array([0, 0, 0, 0, 0])

In [145]:
np.power(arr,arr2)

array([      1,      16,     729,   65536, 1953125])

### Statistical Operation

In [147]:
arr = np.array([2,131,41,41,4,14,1,4144,14,14,1,414,1321,5,115,8710,2614,1451])
arr

array([   2,  131,   41,   41,    4,   14,    1, 4144,   14,   14,    1,
        414, 1321,    5,  115, 8710, 2614, 1451])

In [148]:
len(arr)

18

In [149]:

sum(arr)

19037

In [150]:
np.min(arr)

1

In [151]:
np.max(arr)

8710

In [152]:
np.mean(arr)

1057.611111111111

In [153]:
np.median(arr)

41.0

In [154]:
# standard deviation
np.std(arr)  # find the 

2157.5746450043002

In [155]:
np.var(arr)

4655128.348765432

In [157]:
np.percentile(arr, 25)

7.25

In [159]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [161]:
arr3.transpose()

array([[[ 1,  7],
        [ 4, 10]],

       [[ 2,  8],
        [ 5, 11]],

       [[ 3,  9],
        [ 6, 12]]])